project:
  type: website
  title: "Introduction to Machine Learning"
  # Setting the execution dir allows us to use `data/`
  # instead of relative paths in regular code cells
  execute-dir: project
  # `render` executes and renders modules, slides, and exercises into `_site`
  render:
    - modules/**/*.qmd
    - modules/index.qmd
  # `resources` copies files into `_site` without execution
  resources:
    - styles.scss
    - src/utils.py
    - data

# Setting the pyodide resources allows live code cells to see files
# previously copied into `_site`
# by copying them to the virtual file system used by live coding
pyodide:
  resources:
    - src/utils.py
    - data

website:
  page-navigation: true
  bread-crumbs: false
  repo-url: https://github.com/UBC-MDS/introduction-machine-learning
  repo-actions: [issue]
  sidebar:
    collapse-level: 1
    logo: static/logo.svg
    search: true
    style: 'docked'
    background: 'primary'
    contents:
      - section: "**M0. Welcome to Introduction to Machine Learning**"
        contents:
          - text: '0. Welcome!'
            href: modules/index.qmd
          - href: modules/module0/module0-01-introduction_to_machine_learning.qmd
          - text: '&nbsp;&nbsp; 1.1. Prerequisite confirmation'
            href: modules/module0/module0-02-prerequisite_confirmation.qmd
      - section: "**M1. Machine Learning Terminology**"
        contents:
          - href: modules/module1/module1-00-module_learning_outcomes.qmd
          - href: modules/module1/module1-01-what_is_supervised_machine_learning.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module1/module1-02-is_it_machine_learning.qmd
          - href: modules/module1/module1-03-types_of_machine_learning.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module1/module1-04-sup_vs_unsup_learning.qmd
          - href: modules/module1/module1-05-classification_vs_regression.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module1/module1-06-classification_vs_regression.qmd
          - href: modules/module1/module1-08-tabular_data_and_terminology.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module1/module1-09-terminology.qmd
          - href: modules/module1/module1-13-baselines_training_a_model.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module1/module1-14-building_a_model.qmd
          - href: modules/module1/module1-17-baselines_dummy_regression.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module1/module1-18-dummy_regressors.qmd
          - href: modules/module1/module1-21-what_did_we_just_learn.qmd
      - section: "**M2. Decision Trees**"
        contents:
          - href: modules/module2/module2-00-module_learning_outcomes.qmd
          - href: modules/module2/module2-01-introducing_decision_trees.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module2/module2-02-decision_trees.qmd
          - href: modules/module2/module2-04-building_a_decision_tree_classifier.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module2/module2-05-predicting_with_a_decision_tree.qmd
          - href: modules/module2/module2-08-decision_trees_with_continous_features.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module2/module2-09-decision_boundaries.qmd
          - href: modules/module2/module2-12-parameters_and_hyperparameters.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module2/module2-13-feature_splitting.qmd
          - href: modules/module2/module2-16-decision_tree_regressor.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module2/module2-17-regression_with_decision_tree.qmd
          - href: modules/module2/module2-19-generalization.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module2/module2-20-generalization_practice_questions.qmd
          - href: modules/module2/module2-21-what_did_we_just_learn.qmd
      - section: "**M3. Splitting, Cross-Validation and the Fundamental Tradeoff**"
        contents:
          - href: modules/module3/module3-00-module_learning_outcomes.qmd
          - href: modules/module3/module3-01-splitting_data.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module3/module3-02-splitting_our_data.qmd
          - href: modules/module3/module3-05-train_validation_and_test_split.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module3/module3-06-name_that_split.qmd
          - href: modules/module3/module3-08-cross_validation.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module3/module3-09-cross_validation_questions.qmd
          - href: modules/module3/module3-13-underfitting_and_overfitting.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module3/module3-14-is_it_overfitting_or_underfitting.qmd
          - href: modules/module3/module3-17-fundamental_tradeoff_and_the_golden_rule.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module3/module3-18-quick_questions_on_tradeoff_and_golden_rule.qmd
          - href: modules/module3/module3-21-what_did_we_just_learn.qmd
      - section: "**M4.Similarity-Based Approaches to Supervised Learning**"
        contents:
          - href: modules/module4/module4-00-module_learning_outcomes.qmd
          - href: modules/module4/module4-01-terminology.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module4/module4-02-dimension_questions.qmd
          - href: modules/module4/module4-04-distances.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module4/module4-05-calculating_distances.qmd
          - href: modules/module4/module4-09-finding_the_nearest_neighbour.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module4/module4-10-finding_neighbours_questions.qmd
          - href: modules/module4/module4-13-𝑘-nearest_neighbours_(𝑘-nns)_classifier.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module4/module4-14-classifying_examples_by_hand.qmd
          - href: modules/module4/module4-17-choosing_𝑘_(n_neighbors).qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module4/module4-18-choosing_k_for_your_model.qmd
          - href: modules/module4/module4-21-𝑘_-nearest_neighbours_regressor.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module4/module4-22-regression_questions.qmd
          - href: modules/module4/module4-24-support_vector_machines_(svms)_with_rbf_kernel.qmd
          - text: '&nbsp;&nbsp; 7.1. Exercises'
            href: modules/module4/module4-25-testing_your_svm_rbf_knowledge.qmd
          - href: modules/module4/module4-28-what_did_we_just_learn.qmd
      - section: "**M5. Preprocessing Numerical Features, Pipelines and Hyperparameter Optimization**"
        contents:
          - href: modules/module5/module5-00-module_learning_outcomes.qmd
          - href: modules/module5/module5-01-the_importance_of_preprocessing.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module5/module5-02-questions_on_why.qmd
          - href: modules/module5/module5-05-case_study:_preprocessing_with_imputation.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module5/module5-06-imputation.qmd
          - href: modules/module5/module5-09-case_study:_preprocessing_with_scaling.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module5/module5-10-name_that_scaling_method.qmd
          - href: modules/module5/module5-13-case_study:_pipelines.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module5/module5-14-pipeline_questions.qmd
          - href: modules/module5/module5-17-automated_hyperparameter_optimization.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module5/module5-18-exhaustive_or_randomized_grid_search.qmd
          - href: modules/module5/module5-21-what_did_we_just_learn.qmd
      - section: "**M6. Preprocessing Categorical Variables**"
        contents:
          - href: modules/module6/module6-00-module_learning_outcomes.qmd
          - href: modules/module6/module6-01-categorical_variables:_ordinal_encoding.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module6/module6-02-categorical_variables.qmd
          - href: modules/module6/module6-05-categorical_variables:_one-hot_encoding.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module6/module6-06-one-hot_encoding_questions.qmd
          - href: modules/module6/module6-10-columntransformer.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module6/module6-11-transforming_columns_with_columntransformer.qmd
          - href: modules/module6/module6-14-make_-_pipelines_column_transformers.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module6/module6-15-making_pipelines.qmd
          - href: modules/module6/module6-18-handeling_categorical_features:_binary_ordinal_and_more.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module6/module6-19-transforming_categorical_features.qmd
          - href: modules/module6/module6-22-text_data.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module6/module6-23-text_data_questions.qmd
          - href: modules/module6/module6-26-what_did_we_just_learn.qmd
      - section: "**M7. Assessment and Measurements**"
        contents:
          - href: modules/module7/module7-00-module_learning_outcomes.qmd
          - href: modules/module7/module7-01-introducing_evaluation_metrics.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module7/module7-02-name_that_value.qmd
          - href: modules/module7/module7-05-precision_recall_and_f1_score.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module7/module7-06-lets_calculate.qmd
          - href: modules/module7/module7-09-multi-class_measurements.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module7/module7-10-using_sklearn_to_obtain_different_measurements.qmd
          - href: modules/module7/module7-13-imbalanced_datasets.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module7/module7-14-ture_or_false_unbalanced_data.qmd
          - href: modules/module7/module7-16-regression_measurements.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module7/module7-17-name_that_measurement.qmd
          - href: modules/module7/module7-21-passing_different_scoring_methods.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module7/module7-22-true_or_false_scoring_with_cross-validation.qmd
          - href: modules/module7/module7-24-what_did_we_just_learn.qmd
      - section: "**M8. Linear Models**"
        contents:
          - href: modules/module8/module8-00-module_learning_outcomes.qmd
          - href: modules/module8/module8-01-introducing_linear_regression.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module8/module8-02-linear_regression_questions.qmd
          - href: modules/module8/module8-05-coefficients_and_coef_.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module8/module8-06-linear_model_coefficient_questions.qmd
          - href: modules/module8/module8-09-logistic_regression.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module8/module8-10-logistic_regression_prediction.qmd
          - href: modules/module8/module8-13-predicting_probabilities.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module8/module8-14-probabilities_and_logistic_regression.qmd
          - href: modules/module8/module8-17-multi-class_classification.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module8/module8-18-multi-class_questions.qmd
          - href: modules/module8/module8-21-what_did_we_just_learn.qmd
      - section: "**Module Closing Remarks**"
        contents:
          - href: modules/module9/module9-00-congratulations.qmd

# Since we are declaring options for two formats here (html and revealjs)
# each qmd file needs to include a yaml block including which format to use for that file.
# https://github.com/quarto-dev/quarto-cli/issues/4583
format:
  html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#283791'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  live-html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#283791'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  revealjs:
    theme: styles.scss
    width: 100%
    monofont: Ubuntu Mono
    mainfont: Ubuntu
    font-size: 0.5em
    monobackgroundcolor: '#F1F3F5'
    highlight-style: atom-one
    # tango atom-one  nord
    transition: slide
    controls-layout: bottom-right
    show-notes: true
    slide-number: true
    code-line-numbers: false
    code-copy: true
    progress: false
    history: false
    menu: false
    execute:
      echo: true
