project:
  type: website
  title: "Introduction to Machine Learning"
  # Setting the execution dir allows us to use `data/`
  # instead of relative paths in regular code cells
  execute-dir: project
  # `render` executes and renders modules, slides, and exercises into `_site`
  render:
    - modules/**/*.qmd
    - modules/index.qmd
  # `resources` copies files into `_site` without execution
  resources:
    - styles.scss
    - src/utils.py
    - data

# Setting the pyodide resources allows live code cells to see files
# previously copied into `_site`
# by copying them to the virtual file system used by live coding
pyodide:
  resources:
    - src/utils.py
    - data

website:
  page-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    logo: static/logo.svg
    search: true
    style: 'docked'
    background: 'primary'
    contents:
      - section: "**M1. Machine Learning Terminology**"
        contents:
          - href: modules/module1/module1-01-what_is_supervised_machine_learning.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module1/module1-02-is_it_machine_learning.qmd
          - href: modules/module1/module1-03-building_a_model.qmd
      - section: "**M3. Splitting, Cross-Validation and the Fundamental Tradeoff**"
        contents:
          - href: modules/module3/module3-00-module_learning_outcomes.qmd
          - href: modules/module3/module3-01-splitting_data.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module3/module3-02-splitting_our_data.qmd
          - href: modules/module3/module3-05-train_validation_and_test_split.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module3/module3-06-name_that_split.qmd
          - href: modules/module3/module3-08-cross_validation.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module3/module3-09-cross_validation_questions.qmd
          - href: modules/module3/module3-13-underfitting_and_overfitting.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module3/module3-14-is_it_overfitting_or_underfitting.qmd
          - href: modules/module3/module3-17-fundamental_tradeoff_and_the_golden_rule.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module3/module3-18-quick_questions_on_tradeoff_and_golden_rule.qmd
          - href: modules/module3/module3-21-what_did_we_just_learn.qmd

# Since we are declaring options for two formats here (html and revealjs)
# each qmd file needs to include a yaml block including which format to use for that file.
# https://github.com/quarto-dev/quarto-cli/issues/4583
format:
  html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#F78F2E'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  live-html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#F78F2E'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  revealjs:
    theme: styles.scss
    width: 100%
    monofont: Ubuntu Mono
    mainfont: Ubuntu
    font-size: 0.5em
    monobackgroundcolor: '#F1F3F5'
    highlight-style: atom-one
    # tango atom-one  nord
    transition: slide
    controls-layout: bottom-right
    show-notes: true
    slide-number: true
    code-line-numbers: false
    code-copy: true
    progress: false
    history: false
    menu: false
    execute:
      echo: true