project:
  type: website
  title: "Introduction to Machine Learning"
  # Setting the execution dir allows us to use `data/`
  # instead of relative paths in regular code cells
  execute-dir: project
  # `render` executes and renders modules, slides, and exercises into `_site`
  render:
    - modules/**/*.qmd
    - modules/index.qmd
  # `resources` copies files into `_site` without execution
  resources:
    - styles.scss
    - src/utils.py
    - data

# Setting the pyodide resources allows live code cells to see files
# previously copied into `_site`
# by copying them to the virtual file system used by live coding
pyodide:
  resources:
    - src/utils.py
    - data

website:
  page-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    logo: static/logo.svg
    search: true
    style: 'docked'
    background: 'primary'
    contents:
      - section: "**M1. Machine Learning Terminology**"
        contents:
          - href: modules/module1/module1-01-what_is_supervised_machine_learning.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module1/module1-02-is_it_machine_learning.qmd
          - href: modules/module1/module1-03-building_a_model.qmd
      - section: "**M4.Similarity-Based Approaches to Supervised Learning**"
        contents:
          - href: modules/module4/module4-00-module_learning_outcomes.qmd
          - href: modules/module4/module4-01-terminology.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module4/module4-02-dimension_questions.qmd
          - href: modules/module4/module4-04-distances.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module4/module4-05-calculating_distances.qmd
          - href: modules/module4/module4-09-finding_the_nearest_neighbour.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module4/module4-10-finding_neighbours_questions.qmd
          - href: modules/module4/module4-13-𝑘-nearest_neighbours_(𝑘-nns)_classifier.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module4/module4-14-classifying_examples_by_hand.qmd
          - href: modules/module4/module4-17-choosing_𝑘_(n_neighbors).qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module4/module4-18-choosing_k_for_your_model.qmd
          - href: modules/module4/module4-21-𝑘_-nearest_neighbours_regressor.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module4/module4-22-regression_questions.qmd
          - href: modules/module4/module4-24-support_vector_machines_(svms)_with_rbf_kernel.qmd
          - text: '&nbsp;&nbsp; 7.1. Exercises'
            href: modules/module4/module4-25-testing_your_svm_rbf_knowledge.qmd
          - href: modules/module4/module4-28-what_did_we_just_learn.qmd      

# Since we are declaring options for two formats here (html and revealjs)
# each qmd file needs to include a yaml block including which format to use for that file.
# https://github.com/quarto-dev/quarto-cli/issues/4583
format:
  html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#283791'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  live-html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#283791'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  revealjs:
    theme: styles.scss
    width: 100%
    monofont: Ubuntu Mono
    mainfont: Ubuntu
    font-size: 0.5em
    monobackgroundcolor: '#F1F3F5'
    highlight-style: atom-one
    # tango atom-one  nord
    transition: slide
    controls-layout: bottom-right
    show-notes: true
    slide-number: true
    code-line-numbers: false
    code-copy: true
    progress: false
    history: false
    menu: false
    execute:
      echo: true