project:
  type: website
  title: "Introduction to Machine Learning"
  # Setting the execution dir allows us to use `data/`
  # instead of relative paths in regular code cells
  execute-dir: project
  # `render` executes and renders modules, slides, and exercises into `_site`
  render:
    - modules/**/*.qmd
    - modules/index.qmd
  # `resources` copies files into `_site` without execution
  resources:
    - styles.scss
    - src/utils.py
    - data

# Setting the pyodide resources allows live code cells to see files
# previously copied into `_site`
# by copying them to the virtual file system used by live coding
pyodide:
  resources:
    - src/utils.py
    - data

website:
  page-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    logo: static/logo.svg
    search: true
    style: 'docked'
    background: 'primary'
    contents:
      - section: "**M1. Machine Learning Terminology**"
        contents:
          - href: modules/module1/module1-01-what_is_supervised_machine_learning.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module1/module1-02-is_it_machine_learning.qmd
          - href: modules/module1/module1-03-building_a_model.qmd
      - section: "**M6. Preprocessing Categorical Variables**"
        contents:
          - href: modules/module6/module6-00-module_learning_outcomes.qmd
          - href: modules/module6/module6-01-categorical_variables:_ordinal_encoding.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module6/module6-02-categorical_variables.qmd
          - href: modules/module6/module6-05-categorical_variables:_one-hot_encoding.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module6/module6-06-one-hot_encoding_questions.qmd
          - href: modules/module6/module6-10-columntransformer.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module6/module6-11-transforming_columns_with_columntransformer.qmd
          - href: modules/module6/module6-14-make_-_pipelines_column_transformers.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module6/module6-15-making_pipelines.qmd
          - href: modules/module6/module6-18-handeling_categorical_features:_binary_ordinal_and_more.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module6/module6-19-transforming_categorical_features.qmd
          - href: modules/module6/module6-22-text_data.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module6/module6-23-text_data_questions.qmd
          - href: modules/module6/module6-26-what_did_we_just_learn.qmd

# Since we are declaring options for two formats here (html and revealjs)
# each qmd file needs to include a yaml block including which format to use for that file.
# https://github.com/quarto-dev/quarto-cli/issues/4583
format:
  html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#283791'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  live-html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#283791'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  revealjs:
    theme: styles.scss
    width: 100%
    monofont: Ubuntu Mono
    mainfont: Ubuntu
    font-size: 0.5em
    monobackgroundcolor: '#F1F3F5'
    highlight-style: atom-one
    # tango atom-one  nord
    transition: slide
    controls-layout: bottom-right
    show-notes: true
    slide-number: true
    code-line-numbers: false
    code-copy: true
    progress: false
    history: false
    menu: false
    execute:
      echo: true