project:
  type: website
  title: "Introduction to Machine Learning"
  # Setting the execution dir allows us to use `data/`
  # instead of relative paths in regular code cells
  execute-dir: project
  # `render` executes and renders modules, slides, and exercises into `_site`
  render:
    - modules/**/*.qmd
    - modules/index.qmd
  # `resources` copies files into `_site` without execution
  resources:
    - styles.scss
    - src/utils.py
    - data

# Setting the pyodide resources allows live code cells to see files
# previously copied into `_site`
# by copying them to the virtual file system used by live coding
pyodide:
  resources:
    - src/utils.py
    - data

website:
  page-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    logo: static/logo.svg
    search: true
    style: 'docked'
    background: 'primary'
    contents:
      - section: "**M0. Welcome to Introduction to Machine Learning**"
        contents:
          - text: '0. Welcome!'
            href: modules/index.qmd
          - href: modules/module0/module0-01-introduction_to_machine_learning.qmd
          - text: '&nbsp;&nbsp; 1.1. Prerequisite confirmation'
            href: modules/module0/module0-02-prerequisite_confirmation.qmd
      - section: "**M1. Machine Learning Terminology**"
        contents:
          - href: modules/module1/module1-00-module_learning_outcomes.qmd
          - href: modules/module1/module1-01-what_is_supervised_machine_learning.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module1/module1-02-is_it_machine_learning.qmd
          - href: modules/module1/module1-03-types_of_machine_learning.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module1/module1-04-sup_vs_unsup_learning.qmd
          - href: modules/module1/module1-05-classification_vs_regression.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module1/module1-06-classification_vs_regression.qmd
          - href: modules/module1/module1-08-tabular_data_and_terminology.qmd
          - text: '&nbsp;&nbsp; 4.1. Exercises'
            href: modules/module1/module1-09-terminology.qmd
          - href: modules/module1/module1-13-baselines_training_a_model.qmd
          - text: '&nbsp;&nbsp; 5.1. Exercises'
            href: modules/module1/module1-14-building_a_model.qmd
          - href: modules/module1/module1-17-baselines_dummy_regression.qmd
          - text: '&nbsp;&nbsp; 6.1. Exercises'
            href: modules/module1/module1-18-dummy_regressors.qmd
          - href: modules/module1/module1-21-what_did_we_just_learn.qmd

# Since we are declaring options for two formats here (html and revealjs)
# each qmd file needs to include a yaml block including which format to use for that file.
# https://github.com/quarto-dev/quarto-cli/issues/4583
format:
  html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#F78F2E'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  live-html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#F78F2E'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  revealjs:
    theme: styles.scss
    width: 100%
    monofont: Ubuntu Mono
    mainfont: Ubuntu
    font-size: 0.5em
    monobackgroundcolor: '#F1F3F5'
    highlight-style: atom-one
    # tango atom-one  nord
    transition: slide
    controls-layout: bottom-right
    show-notes: true
    slide-number: true
    code-line-numbers: false
    code-copy: true
    progress: false
    history: false
    menu: false
    execute:
      echo: true