---
format: html
---

# Welcome to Introduction to Machine Learning!

This course is part of the [Key Capabilities for Data Science program](https://extendedlearning.ubc.ca/programs/key-capabilities-data-science) and covers topics related to machine learning; a topic closely related to artificial intelligence (AI), data science, and statistics. 

This course covers the data science perspective on the introductory concepts in machine learning, with a focus on making predictions. Not only does it cover different models such as K-NN, decision trees and linear classifiers, but it also tackles important concepts needed to prepare and preprocess data before building them. No course would be complete without knowing how to read the results. We cover different ways to evaluate your model and when to question your results. Finally, we show you how to streamline the entire process by implementing pipelines in your workflow.

Course prerequisites: [Programming in Python for Data Science](https://prog-learn.mds.ubc.ca/)