---
format: html
---

<script src='../../src/quiz.js'></script>

# 6.1. Exercises

## Generalization Practice Questions

<div id='mcq1'></div>
<script>
    generateQuiz(
        'mcq1',
        'Question 1',
        'Is it always a good idea to have the most precise/complex model?',
        {
        'Yes, it will predict the best in all cases.': 'Complex models have the best scores for the data that it has seen but what about unseen data?',
        'Yes, precise models result in the highest accuracy': 'Precise models have the highest accuracy for the data that it has seen but what about unseen data?',
        'No, it may not generalize well to other unseen data.': '',
        'No, you want a model with low accuracy': 'You are on the right track but you still want a model that does its job well.',
        },
        'No, it may not generalize well to other unseen data.',
    );
</script>

<div id='mcq2'></div>
<script>
    generateQuiz(
        'mcq2',
        'Question 2',
        'Does increasing the depth of a tree make the tree more or less generalized?',
        {
        'More generalized': 'Increasing the depth increases the number of decision boundaries. Does this make the model more generalized then?',
        'Less generalized': ''
        },
        'Less generalized',
    );
</script>

