---
format: revealjs
title: Congratulations on completing Introduction to Machine Learning!

title-slide-attributes:
  data-notes: |
---

```{python}
#  | echo: false
%run src/utils.py
```

## You did it!

We covered a lot of ground but you managed to finished all 8 Modules. It's important to celebrate this success. 


---

## Attribution

- Material from UBC's <a href="https://github.com/UBC-MDS/DSCI_571_sup-learn-1" target="_blank">DSCI 571: Supervised Learning I</a> by <a href="https://kvarada.github.io/" target="_blank">Varada Kolhatkar</a>.
- Material from UBC's <a href="https://github.com/UBC-CS/cpsc330" target="_blank">CPSC330 course</a> by <a href="www.mikegelbart.com" target="_blank">Mike Gelbart</a>.
- Material originally from UBC's <a href="https://www.cs.ubc.ca/~schmidtm/Courses/340-F19/" target="_blank">CPSC340 course</a>  by <a href="https://www.cs.ubc.ca/~schmidtm/" target="_blank"> Mark Schmidt</a>.


---

## Special Thanks 

Not only did you put in a lot of work by completing this course, but many people did too by helping make this course possible. 

Special thanks must be attributed to the following individuals and organizations (in alphabetical order):

- <a href="https://www.tomasbeuzen.com/" target="_blank"> Tom Beuzen</a> 
- <a href="https://betatim.github.io/" target="_blank">Tim Head</a>  
- <a href="https://ines.io/" target="_blank">Ines Montani</a> 
- <a href="https://joelostblom.com/" target="_blank">Joel Ostblom</a> 
- <a href="https://www.tiffanytimbers.com/" target="_blank"> Tiffany Timbers</a> 
- <a href="https://www.linkedin.com/in/elijah-willie-203845b9/?originalSubdomain=ca" target="_blank">Elijah Willie</a>

- The Master of Data Science Program at UBC
- Our friends, family and colleagues for supporting us and cheering us on!
- All those who gave us feedback and suggestions on how we can improve this course. 

---

## About Us

<br>

### Mike Gelbart

- Website: <a href="https://www.mikegelbart.com/" target="_blank">www.mikegelbart.com</a> 
- Twitter: <a href="https://twitter.com/mikegelbart" target="_blank">@MikeGelbart</a> 
<br>
<br>

### Varada Kolhatkar 

- Website: <a href="https://kvarada.github.io/" target="_blank">https://kvarada.github.io/</a> 
- Twitter: <a href="https://twitter.com/varadakolhatkar" target="_blank">@varadakolhatkar</a> 
<br>
<br>

### Hayley Boyce 

- Website: <a href="https://www.hayleyfboyce.com" target="_blank">www.hayleyfboyce.com</a>
- Twitter: <a href="https://twitter.com/hayleyfboyce" target="_blank">@HayleyFBoyce</a> 


# Good luck on applying your new skills!